"""Simulates 2D electrostatic fields and potentials generated by discrete point charges."""

import math
from typing import List, Tuple

EPSILON_0 = 8.8541878128e-12  # Permittivity of free space in Farads per meter


class PointCharge:
    """Represents a discrete electrostatic point charge in 2D space."""

    def __init__(self, charge_coulombs: float, pos_x: float, pos_y: float) -> None:
        """Initializes charge magnitude and spatial coordinate.
        
        Args:
            charge_coulombs (float): Electrical charge magnitude in Coulombs.
            pos_x (float): Cartesian X position in meters.
            pos_y (float): Cartesian Y position in meters.
        """
        self.q = charge_coulombs
        self.x = pos_x
        self.y = pos_y


class ElectrostaticSolver:
    """Calculates potential and electric field vectors using Coulomb superposition."""

    def __init__(self, charges: List[PointCharge]) -> None:
        """Initializes the solver with a list of discrete charges.
        
        Args:
            charges (List[PointCharge]): Array of point charge instances.
        """
        self.charges = charges

    def calculatePotential(self, x: float, y: float) -> float:
        """Computes scalar electrostatic potential at target coordinate (x, y).
        
        Args:
            x (float): X coordinate in meters.
            y (float): Y coordinate in meters.
            
        Returns:
            float: Scalar potential in Volts.
        """
        potential = 0.0
        k_e = 1.0 / (4.0 * math.pi * EPSILON_0)

        for charge in self.charges:
            dx = x - charge.x
            dy = y - charge.y
            dist = math.hypot(dx, dy)
            if dist < 1e-6:
                continue  # Avoids division by zero singularity at charge center
            potential += k_e * charge.q / dist

        return potential

    def calculateElectricField(self, x: float, y: float) -> Tuple[float, float]:
        """Calculates the vector electric field components (Ex, Ey) at (x, y).
        
        Args:
            x (float): X coordinate in meters.
            y (float): Y coordinate in meters.
            
        Returns:
            Tuple[float, float]: Vector field components (Ex, Ey) in V/m.
        """
        e_x = 0.0
        e_y = 0.0
        k_e = 1.0 / (4.0 * math.pi * EPSILON_0)

        for charge in self.charges:
            dx = x - charge.x
            dy = y - charge.y
            dist = math.hypot(dx, dy)
            if dist < 1e-6:
                continue  # Bypasses point singularity

            # Electric field points away from positive charge (E = k * q / r^2 * r_hat)
            e_mag = k_e * charge.q / (dist * dist)
            e_x += e_mag * (dx / dist)
            e_y += e_mag * (dy / dist)

        return e_x, e_y


def main() -> None:
    """Executes field evaluation on an electric dipole configuration."""
    # Dipole: +1 nC at (0, 0.05) and -1 nC at (0, -0.05)
    dipole_charges = [
        PointCharge(1e-9, 0.0, 0.05),
        PointCharge(-1e-9, 0.0, -0.05)
    ]
    solver = ElectrostaticSolver(dipole_charges)

    test_points = [
        (0.1, 0.0),
        (0.2, 0.0),
        (0.0, 0.1),
        (0.0, -0.1)
    ]

    print(f"{'Point (x, y) [m]':<20}{'Potential [V]':<16}{'|E| [V/m]':<14}")
    print("-" * 50)
    for px, py in test_points:
        pot = solver.calculatePotential(px, py)
        ex, ey = solver.calculateElectricField(px, py)
        e_mag = math.hypot(ex, ey)
        point_str = f"({px:.2f}, {py:.2f})"
        print(f"{point_str:<20}{pot:<16.3f}{e_mag:<14.3f}")


if __name__ == "__main__":
    main()

